services:
  - type: web
    name: coin-clash-telegram-holder-bot
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
